"""Shared research-side helpers used by both Stage 7.5 and Stage 8.

Lives in `lib/` (not in either `pipeline/` module) so the two consumers
(`pipeline/deep_research_v2.py` for Parallel AI brief assembly and
`pipeline/deep_analysis.py` for Stage 8 prompt assembly) can both import
the SAME function object — the canonical implementation of gate-file
parsing has exactly one home.

Architectural rule: pipeline modules MUST NOT import from each other for
shared helpers. They both import from this module instead.
"""

from pathlib import Path


def _format_gate_signals(gate_path: Path) -> str:
    """Parse 2_research/{slug}/gate_build.md into a human-readable signal block.

    Returns an explicit placeholder string when the file is missing or
    unparseable so that downstream prompts still read well. Never raises —
    the pipeline must not block on a single missing/malformed gate file.

    Output format (exact — consumed byte-for-byte by prompts):
        - cis_gap_confirmed: False
        - replicable_confirmed: False
        - oss_base_available: False
        - market_demand_signals: True
        - clear_localization_path: False
        Decision: build_analysis_ready=False, build_priority=medium
    """
    if not gate_path.exists():
        return "(Stage 7 gate signals not available)"
    try:
        text = gate_path.read_text(encoding="utf-8")
    except Exception:
        return "(Stage 7 gate signals not available — read error)"

    # Extract all "- key: value" lines that sit under ## Build Signals and ## Decision.
    # The file is small and deterministic (generated by build_gate.py) so a
    # line-by-line scan is simpler than regex and easier to debug.
    signals: list[str] = []
    decision: list[str] = []
    section: str | None = None
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("## Build Signals"):
            section = "signals"
            continue
        if s.startswith("## Decision"):
            section = "decision"
            continue
        if s.startswith("## "):
            section = None
            continue
        if section == "signals" and s.startswith("- "):
            signals.append(s)
        elif section == "decision" and s.startswith("- "):
            decision.append(s.lstrip("- "))

    if not signals and not decision:
        return "(Stage 7 gate signals not available — no parseable content)"

    parts: list[str] = list(signals)
    if decision:
        parts.append("Decision: " + ", ".join(decision))
    return "\n".join(parts)
