"""Shared research-side helpers used by both Stage 7.5 and Stage 8.

Lives in `lib/` (not in either `pipeline/` module) so the two consumers
(`pipeline/deep_research_v2.py` for Parallel AI brief assembly and
`pipeline/deep_analysis.py` for Stage 8 prompt assembly) can both import
the SAME function object — the canonical implementation of gate-file
parsing has exactly one home.

Architectural rule: pipeline modules MUST NOT import from each other for
shared helpers. They both import from this module instead.
"""

import json
from pathlib import Path


def _format_gate_signals(gate_path: Path) -> str:
    """Parse 2_research/{slug}/gate_build.md into a human-readable signal block.

    Returns an explicit placeholder string when the file is missing or
    unparseable so that downstream prompts still read well. Never raises —
    the pipeline must not block on a single missing/malformed gate file.

    Output format (exact — consumed byte-for-byte by prompts):
        - cis_gap_confirmed: False
        - replicable_confirmed: False
        - oss_base_available: False
        - market_demand_signals: True
        - clear_localization_path: False
        Decision: build_analysis_ready=False, build_priority=medium
    """
    if not gate_path.exists():
        return "(Stage 7 gate signals not available)"
    try:
        text = gate_path.read_text(encoding="utf-8")
    except Exception:
        return "(Stage 7 gate signals not available — read error)"

    # Extract all "- key: value" lines that sit under ## Build Signals and ## Decision.
    # The file is small and deterministic (generated by build_gate.py) so a
    # line-by-line scan is simpler than regex and easier to debug.
    signals: list[str] = []
    decision: list[str] = []
    section: str | None = None
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("## Build Signals"):
            section = "signals"
            continue
        if s.startswith("## Decision"):
            section = "decision"
            continue
        if s.startswith("## "):
            section = None
            continue
        if section == "signals" and s.startswith("- "):
            signals.append(s)
        elif section == "decision" and s.startswith("- "):
            decision.append(s.lstrip("- "))

    if not signals and not decision:
        return "(Stage 7 gate signals not available — no parseable content)"

    parts: list[str] = list(signals)
    if decision:
        parts.append("Decision: " + ", ".join(decision))
    return "\n".join(parts)


def _format_raw_evidence(raw_path: Path, max_chars: int = 6000) -> str:
    """Compact `build_research_raw.json` into a prompt-friendly evidence block.

    Why: feeding only the LLM-synthesized markdown re-anchors Parallel AI on
    the cheap layer's interpretation. Feeding raw JSON's independent evidence
    (titles + URLs + short snippets across all buckets) lets Parallel AI form
    its own opinion before seeing our synthesis.

    Per-result format:
        - <url>
          <title[:200]>
          <snippet[:200]>

    Returns documented placeholder when file missing/unreadable/malformed.
    Never raises.
    """
    if not raw_path.exists():
        return "(Stage 5 raw evidence not available)"
    try:
        payload = json.loads(raw_path.read_text(encoding="utf-8"))
    except OSError:
        return "(Stage 5 raw evidence not available — read error)"
    except json.JSONDecodeError:
        return "(Stage 5 raw evidence not available — malformed JSON)"
    buckets = payload.get("buckets") or {}
    if not isinstance(buckets, dict) or not buckets:
        return "(Stage 5 raw evidence not available — no buckets)"

    bucket_order = ["CIS_PLAYERS", "DEMAND_SIGNAL", "GLOBAL_ALT", "OSS_BASE", "COMMUNITY"]
    seen = set(bucket_order)
    ordered = [b for b in bucket_order if b in buckets] + [
        b for b in buckets.keys() if b not in seen
    ]

    out: list[str] = []
    for bucket_name in ordered:
        bucket = buckets.get(bucket_name) or {}
        results = bucket.get("results") or []
        query = bucket.get("query", "")
        out.append(f"=== {bucket_name} (query: {query!r}, n={len(results)}) ===")
        for r in results:
            url = (r.get("url") or "").strip()
            title = (r.get("title") or "").strip().replace("\n", " ")
            snippet = (r.get("text") or "").strip().replace("\n", " ")
            out.append(f"- {url}")
            if title:
                out.append(f"  {title[:200]}")
            if snippet:
                out.append(f"  {snippet[:200]}")

    text = "\n".join(out)
    if len(text) > max_chars:
        text = text[:max_chars] + f"\n[... truncated to {max_chars} chars ...]"
    return text
